# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='contact',
            new_name='preferred_contact',
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cl_app.City'),
        ),
    ]
