# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0002_auto_20160624_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='city',
            new_name='profile_city',
        ),
        migrations.AlterField(
            model_name='listingtype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcat', to='cl_app.ListingType'),
        ),
    ]
