# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 21:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0002_auto_20160623_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='city',
        ),
        migrations.RemoveField(
            model_name='type',
            name='city',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
