# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0003_auto_20160623_2101'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='ListingType',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='type',
            new_name='listing_type',
        ),
        migrations.RenameField(
            model_name='listingtype',
            old_name='type',
            new_name='listing_type',
        ),
    ]
