# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0003_auto_20160625_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preferred_contact',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cl_app.City', verbose_name='Preferred City'),
        ),
    ]
