# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0004_auto_20160626_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-created']},
        ),
    ]
